# Generated by Django 5.1.6 on 2025-05-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Invoice', 'Invoice'), ('CreditNote', 'Credit Note'), ('Purchase', 'Purchase'), ('DebitNote', 'Debit Note')], max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
