# Generated by Django 5.1.6 on 2025-05-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0002_initial'),
        ('sales', '0004_alter_creditnote_credit_note_no_and_more'),
        ('users', '0002_business_isgstregistered'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Invoice', 'Invoice'), ('CreditNote', 'Credit Note'), ('Purchase', 'Purchase'), ('DebitNote', 'Debit Note')], max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='users.business')),
                ('creditnote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='sales.creditnote')),
                ('debitnote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='purchase.debitnote')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='sales.invoice')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='purchase.purchase')),
            ],
        ),
    ]
