# Generated by Django 5.1.6 on 2025-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttracking',
            name='document_type',
            field=models.CharField(choices=[('Invoice', 'Invoice'), ('CreditNote', 'Credit Note'), ('Purchase', 'Purchase'), ('DebitNote', 'Debit Note')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
