# Generated by Django 5.1.6 on 2025-05-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0002_initial'),
        ('sales', '0002_initial'),
        ('tracking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttracking',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='users.business'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='creditnote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='sales.creditnote'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='debitnote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='purchase.debitnote'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='documenttracking',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='purchase.purchase'),
        ),
    ]
