# Generated by Django 5.1.6 on 2025-05-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_documenttracking_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttracking',
            name='status',
            field=models.CharField(choices=[('Unseen', 'Unseen'), ('Seen', 'Seen')], default='Unseen', max_length=20),
        ),
    ]
