# Generated by Django 5.1.6 on 2025-05-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_documenttracking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttracking',
            name='status',
        ),
    ]
