# Generated by Django 5.1.6 on 2025-05-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
        ('sales', '0004_alter_creditnote_credit_note_no_and_more'),
        ('tracking', '0004_remove_documenttracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttracking',
            name='creditnote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='sales.creditnote'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='debitnote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='purchase.debitnote'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='documenttracking',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='purchase.purchase'),
        ),
    ]
