# Generated by Django 5.1.6 on 2025-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_cd', models.CharField(max_length=10, unique=True)),
                ('hsn_description', models.TextField()),
            ],
        ),
    ]
