# Generated by Django 5.1.6 on 2025-06-02 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='is_permanently_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='business',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'business')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['user', 'business'], name='users_role_user_id_ae38cf_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_removed'], name='users_role_is_remo_1ccfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_permanently_removed'], name='users_role_is_perm_9c9a36_idx'),
        ),
    ]
