# Generated by Django 5.1.6 on 2025-05-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
