# Generated by Django 5.1.6 on 2025-05-08 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_stock_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='stock_updated',
        ),
    ]
