# Generated by Django 5.1.6 on 2025-05-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_initial'),
        ('sales', '0004_remove_invoice_stock_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='parties.party'),
        ),
    ]
